//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rpc.Bulletin.Maker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\david\\Desktop\\RPC Bulletin Builder\\SourceFiles")]
        public string SourceFilesFolder {
            get {
                return ((string)(this["SourceFilesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\david\\Desktop\\RPC Bulletin Builder\\SourceCode\\Rpc.TeX.Library\\RPC-Bullet" +
            "in-AM.tex")]
        public string TeXMorningBulletinTemplate {
            get {
                return ((string)(this["TeXMorningBulletinTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\david\\Desktop\\RPC Bulletin Builder\\SourceCode\\Rpc.TeX.Library\\RPC-Bullet" +
            "in-PM.tex")]
        public string TeXEveningBulletinTemplate {
            get {
                return ((string)(this["TeXEveningBulletinTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\david\\Desktop\\RPC Bulletin Builder\\TeXFiles")]
        public string TeXFileFolder {
            get {
                return ((string)(this["TeXFileFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\david\\Desktop\\RPC Bulletin Builder\\miktex-portable\\texmfs\\install\\miktex" +
            "\\bin\\x64\\xelatex.exe")]
        public string PdfGeneratorExe {
            get {
                return ((string)(this["PdfGeneratorExe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\david\\Desktop\\RPC Bulletin Builder\\TargetFiles")]
        public string TargetFilesFolder {
            get {
                return ((string)(this["TargetFilesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\david\\Desktop\\RPC Bulletin Builder\\miktex-portable\\texmfs\\install\\miktex" +
            "\\bin\\x64\\texworks.exe")]
        public string TeXWorksExe {
            get {
                return ((string)(this["TeXWorksExe"]));
            }
        }
    }
}
